### ISSUE TITLE
Disable/Enable specific logging levels

### ISSUE THREAD

**Issue by nkoterba** [lluvio/vue-logger#1]
Hi!

Great simple logger! 👍 👍 

A future enhancement might be to allow configuring which log levels are enabled versus just a single dev/no-dev mode.

**Comment by lluvio** [comment]
@nkoterba 
I'm sorry to reply too slowly. I have added this configuration before. See here [options](https://github.com/lluvio/vue-logger/blob/master/README_EN.md#options)
Thank you for your compliment!
