### ISSUE TITLE
vLogger.installed 作用是？

### ISSUE THREAD

**Issue by GrowingFun** [lluvio/vue-logger#6]
Vue官网说明：Vue.use 会自动阻止多次注册相同插件，届时只会注册一次该插件。
所以if (vLogger.installed) return; 的作用是什么？

**Comment by lluvio** [comment]
@GrowingFun 感谢您的问题。十分不好意思！不知道为什么github的issue 我都没有收到邮件。
这个主要是为了兼容 vue 1.x，1.x 还不会自动阻止的
https://github.com/vuejs/vuejs.org/blob/1.0/src/guide/plugins.md
